In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
%matplotlib inline

In [2]:
DATA_DIR = '../project'
FILE_NAME = 'healthcareClanedTrain3.csv'
data_path = os.path.join(DATA_DIR, FILE_NAME)
health_cleaned = pd.read_csv(data_path)
health_cleaned.head()

hosp_code  hosp_type  city_code  hosp_region  rooms_available  department  \
0          8          0          3            0                3           0   
1          2          0          5            0                2           0   
2         10          1          1            1                2           1   
3         26          2          2            2                2           0   
4         26          2          2            2                2           0   

   ward_type  ward_code  bed_grade  patient_id  admission_type  severity  \
0          0          0          2       31397               0         0   
1          1          0          2       31397               1         0   
2          1          1          2       31397               1         0   
3          0          2          2       31397               1         0   
4          1          2          2       31397               1         0   

   num_visitors  age  deposit  stay  
0             2    5     4911     0  
1             2    5     5954     4  
2             2    5     4745     3  
3             2    5     7272     4  
4             2    5     5558     4

In [3]:
health_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318325 entries, 0 to 318324
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   hosp_code        318325 non-null  int64
 1   hosp_type        318325 non-null  int64
 2   city_code        318325 non-null  int64
 3   hosp_region      318325 non-null  int64
 4   rooms_available  318325 non-null  int64
 5   department       318325 non-null  int64
 6   ward_type        318325 non-null  int64
 7   ward_code        318325 non-null  int64
 8   bed_grade        318325 non-null  int64
 9   patient_id       318325 non-null  int64
 10  admission_type   318325 non-null  int64
 11  severity         318325 non-null  int64
 12  num_visitors     318325 non-null  int64
 13  age              318325 non-null  int64
 14  deposit          318325 non-null  int64
 15  stay             318325 non-null  int64
dtypes: int64(16)
memory usage: 38.9 MB


In [4]:
health_cleaned['stay'].unique()

array([ 0,  4,  3,  1,  5,  2,  7, 10,  8,  6,  9])

In [5]:
health_cleaned['age'].unique()

array([5, 7, 3, 4, 8, 6, 2, 1, 0, 9])

In [9]:
X=health_cleaned.drop('stay',axis=1)
y=health_cleaned['stay']
X.head()

hosp_code  hosp_type  city_code  hosp_region  rooms_available  department  \
0          8          0          3            0                3           0   
1          2          0          5            0                2           0   
2         10          1          1            1                2           1   
3         26          2          2            2                2           0   
4         26          2          2            2                2           0   

   ward_type  ward_code  bed_grade  patient_id  admission_type  severity  \
0          0          0          2       31397               0         0   
1          1          0          2       31397               1         0   
2          1          1          2       31397               1         0   
3          0          2          2       31397               1         0   
4          1          2          2       31397               1         0   

   num_visitors  age  deposit  
0             2    5     4911  
1             2    5     5954  
2             2    5     4745  
3             2    5     7272  
4             2    5     5558

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.10, random_state=42)

In [11]:
y_train.mean()

2.6995343674517964

In [12]:
y_test.mean()

2.688436528131185

## Decision Tree

In [13]:
from sklearn.tree import DecisionTreeClassifier
class_tree = DecisionTreeClassifier(max_depth=11)
class_tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=11)

In [15]:
#Main diagnol = What we got right
#Off = What we got wrong
from sklearn.metrics import confusion_matrix
y_train_pred = class_tree.predict(X_train)
confusion_matrix(y_train,y_train_pred)

array([[ 3688,  9012,  8316,   139,     1,    53,     0,     1,     0,
            0,     0],
       [ 1597, 36520, 27178,  2798,    14,  2051,     1,    18,    27,
            0,     7],
       [ 1299, 24225, 51019,   925,    12,  1014,     2,    10,   143,
            0,    75],
       [  817,  9996, 19261, 11990,    21,  7276,     2,    38,   116,
            1,   109],
       [  330,  2452,  6332,   584,    76,   694,     2,    11,    46,
            8,    62],
       [  350,  2782,  4743,  7604,    19, 15033,     2,    47,   679,
            6,   360],
       [   61,   440,  1245,   197,     8,   375,    31,    14,    38,
            3,    46],
       [  118,   675,  1021,  2041,     9,  4277,     6,   387,   143,
            4,   559],
       [   51,   194,   224,   506,     2,  1783,     1,    27,  1191,
            4,   308],
       [   26,   157,   304,   461,     4,  1136,     2,    50,    33,
          128,   203],
       [   62,   283,   340,   492,     7,  1671,     2,   1

In [16]:
pd.crosstab(y_train, y_train_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted     0      1       2      3    4      5   6    7     8    9    10  \
True                                                                          
0          3688   9012    8316    139    1     53   0    1     0    0     0   
1          1597  36520   27178   2798   14   2051   1   18    27    0     7   
2          1299  24225   51019    925   12   1014   2   10   143    0    75   
3           817   9996   19261  11990   21   7276   2   38   116    1   109   
4           330   2452    6332    584   76    694   2   11    46    8    62   
5           350   2782    4743   7604   19  15033   2   47   679    6   360   
6            61    440    1245    197    8    375  31   14    38    3    46   
7           118    675    1021   2041    9   4277   6  387   143    4   559   
8            51    194     224    506    2   1783   1   27  1191    4   308   
9            26    157     304    461    4   1136   2   50    33  128   203   
10           62    283     340    492    7   1671   2  112   459   58  2519   
All        8399  86736  119983  27737  173  35363  51  715  2875  212  4248   

Predicted     All  
True               
0           21210  
1           70211  
2           78724  
3           49627  
4           10597  
5           31625  
6            2458  
7            9240  
8            4291  
9            2504  
10           6005  
All        286492

In [17]:
#Comparing actual vs predicted values
#On average, can predict correctly 42.8% of the time
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_true=y_train, y_pred=y_train_pred)
accuracy.round(3)

0.428

In [18]:
#43.9% classified 0 stay, actually were 0 stay...
from sklearn.metrics import precision_score
precision = precision_score(y_true=y_train, y_pred=y_train_pred, average = None)
precision.round(3)

array([0.439, 0.421, 0.425, 0.432, 0.439, 0.425, 0.608, 0.541, 0.414,
       0.604, 0.593])

In [19]:
#17.4% of the things that are actually 0 stay, we were able to correctly categorize...
from sklearn.metrics import recall_score
recall = recall_score(y_true=y_train, y_pred=y_train_pred, average = None)
recall.round(3)

array([0.174, 0.52 , 0.648, 0.242, 0.007, 0.475, 0.013, 0.042, 0.278,
       0.051, 0.419])

In [20]:
#What the effect of each feature to the overall classification
#num_visitors, majority of our entropy
pd.Series(data=class_tree.feature_importances_, index=X_train.columns).sort_values(ascending=False).round(3)

num_visitors       0.408
ward_type          0.208
deposit            0.076
bed_grade          0.065
admission_type     0.063
ward_code          0.033
hosp_code          0.033
patient_id         0.027
severity           0.022
rooms_available    0.016
age                0.015
city_code          0.012
hosp_type          0.010
department         0.006
hosp_region        0.005
dtype: float64

## Decision Tree - Test

In [21]:
y_test_pred = class_tree.predict(X_test)
confusion_matrix(y_test,y_test_pred)

array([[ 341, 1066,  946,   24,    1,   14,    0,    0,    0,    0,    0],
       [ 218, 3889, 3207,  338,    2,  248,    0,    4,    2,    0,    1],
       [ 165, 2726, 5549,  124,    2,  139,    0,    2,   16,    0,    7],
       [  96, 1139, 2082, 1302,    2,  838,    1,   11,   20,    0,   19],
       [  44,  267,  683,   64,    1,   67,    0,    0,    3,    2,    7],
       [  35,  315,  513,  828,    0, 1546,    2,    4,   95,    0,   42],
       [   6,   67,  129,   17,    0,   49,    1,    0,    7,    0,    6],
       [  18,   81,  112,  208,    0,  489,    0,   16,   18,    2,   66],
       [   2,   24,   33,   66,    1,  238,    4,    2,  115,    0,   61],
       [   4,   17,   33,   48,    1,  120,    0,    6,    3,    6,   22],
       [   4,   31,   39,   54,    0,  207,    2,   20,   58,    8,  253]])

In [22]:
pd.crosstab(y_test, y_test_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted    0     1      2     3   4     5   6   7    8   9   10    All
True                                                                    
0          341  1066    946    24   1    14   0   0    0   0    0   2392
1          218  3889   3207   338   2   248   0   4    2   0    1   7909
2          165  2726   5549   124   2   139   0   2   16   0    7   8730
3           96  1139   2082  1302   2   838   1  11   20   0   19   5510
4           44   267    683    64   1    67   0   0    3   2    7   1138
5           35   315    513   828   0  1546   2   4   95   0   42   3380
6            6    67    129    17   0    49   1   0    7   0    6    282
7           18    81    112   208   0   489   0  16   18   2   66   1010
8            2    24     33    66   1   238   4   2  115   0   61    546
9            4    17     33    48   1   120   0   6    3   6   22    260
10           4    31     39    54   0   207   2  20   58   8  253    676
All        933  9622  13326  3073  10  3955  10  65  337  18  484  31833

In [23]:
#Comparing actual vs predicted values
#On average, can predict correctly 40.9 of the time
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_true=y_test, y_pred=y_test_pred)
accuracy.round(3)

0.409

In [24]:
#36.4% classified 0 stay, actually were 0 stay...
from sklearn.metrics import precision_score
precision = precision_score(y_true=y_test, y_pred=y_test_pred, average = None)
precision.round(3)

array([0.365, 0.404, 0.416, 0.424, 0.1  , 0.391, 0.1  , 0.246, 0.341,
       0.333, 0.523])

In [25]:
#14.3% of the things that are actually 0 stay, we were able to correctly categorize...
from sklearn.metrics import recall_score
recall = recall_score(y_true=y_test, y_pred=y_test_pred, average = None)
recall.round(3)

array([0.143, 0.492, 0.636, 0.236, 0.001, 0.457, 0.004, 0.016, 0.211,
       0.023, 0.374])

## Naive Bayes

In [26]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, y_train)
y_train_pred_nb = nb.predict(X_train)
confusion_matrix(y_train,y_train_pred_nb)

array([[   22,  6970, 13921,   269,     1,    27,     0,     0,     0,
            0,     0],
       [    6, 19719, 48035,  1257,     0,  1168,     0,     0,     0,
            0,    26],
       [    9, 12772, 64102,   891,     1,   791,     1,     0,     1,
            0,   156],
       [    3, 10238, 31530,  3453,     1,  4202,     0,     0,     1,
            0,   199],
       [    1,  1448,  8257,   385,     0,   410,     1,     0,     0,
            0,    95],
       [    2,  5033, 15364,  3773,     1,  6940,     0,     0,     0,
            0,   512],
       [    1,   233,  1702,   164,     0,   293,     0,     0,     0,
            0,    65],
       [    1,  1220,  4312,  1054,     0,  2124,     0,     0,     0,
            0,   529],
       [    0,   211,   588,   597,     0,  2472,     0,     0,     1,
            0,   422],
       [    0,   264,  1167,   277,     0,   452,     0,     0,     0,
            0,   344],
       [    1,   298,  1035,   422,     2,  2407,     0,    

In [27]:
#Doesn't predict 7 or 9
pd.crosstab(y_train, y_train_pred_nb, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted   0      1       2      3  4      5  6  8    10     All
True                                                             
0          22   6970   13921    269  1     27  0  0     0   21210
1           6  19719   48035   1257  0   1168  0  0    26   70211
2           9  12772   64102    891  1    791  1  1   156   78724
3           3  10238   31530   3453  1   4202  0  1   199   49627
4           1   1448    8257    385  0    410  1  0    95   10597
5           2   5033   15364   3773  1   6940  0  0   512   31625
6           1    233    1702    164  0    293  0  0    65    2458
7           1   1220    4312   1054  0   2124  0  0   529    9240
8           0    211     588    597  0   2472  0  1   422    4291
9           0    264    1167    277  0    452  0  0   344    2504
10          1    298    1035    422  2   2407  0  1  1839    6005
All        46  58406  190013  12542  6  21286  2  4  4187  286492

In [28]:
#Comparing actual vs predicted values
#On average, can predict correctly 33.5% of the time
accuracy = accuracy_score(y_true=y_train, y_pred=y_train_pred_nb)
accuracy.round(3)

0.335

In [29]:
#47.8% classified 0 stay, actually were 0 stay...
precision = precision_score(y_true=y_train, y_pred=y_train_pred_nb, average = None)
precision.round(3)

/Users/dannica/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([0.478, 0.338, 0.337, 0.275, 0.   , 0.326, 0.   , 0.   , 0.25 ,
       0.   , 0.439])

In [30]:
#0.1% of the things that are actually 0 stay, we were able to correctly categorize...
recall = recall_score(y_true=y_train, y_pred=y_train_pred_nb, average = None)
recall.round(3)

array([0.001, 0.281, 0.814, 0.07 , 0.   , 0.219, 0.   , 0.   , 0.   ,
       0.   , 0.306])

## Naive Bayes - Test

In [31]:
y_test_pred_nb = nb.predict(X_test)
confusion_matrix(y_test,y_test_pred_nb)

array([[   1,  768, 1588,   34,    0,    1,    0,    0,    0,    0,    0],
       [   0, 2241, 5368,  173,    0,  125,    0,    0,    0,    0,    2],
       [   1, 1352, 7162,  115,    0,   89,    0,    0,    0,    0,   11],
       [   1, 1099, 3488,  417,    0,  482,    0,    0,    0,    0,   23],
       [   0,  143,  906,   35,    0,   43,    0,    0,    0,    0,   11],
       [   0,  515, 1678,  395,    0,  734,    0,    0,    0,    0,   58],
       [   0,   30,  187,   29,    0,   28,    0,    0,    0,    0,    8],
       [   0,  139,  479,  119,    0,  223,    0,    0,    0,    0,   50],
       [   0,   29,   67,   68,    0,  323,    0,    0,    0,    0,   59],
       [   0,   29,  132,   23,    0,   50,    0,    0,    0,    0,   26],
       [   0,   27,  115,   45,    0,  279,    0,    0,    1,    0,  209]])

In [32]:
#Doesn't predict 4, 6, 7, 9
pd.crosstab(y_test, y_test_pred_nb, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted  0     1      2     3     5  8   10    All
True                                                
0          1   768   1588    34     1  0    0   2392
1          0  2241   5368   173   125  0    2   7909
2          1  1352   7162   115    89  0   11   8730
3          1  1099   3488   417   482  0   23   5510
4          0   143    906    35    43  0   11   1138
5          0   515   1678   395   734  0   58   3380
6          0    30    187    29    28  0    8    282
7          0   139    479   119   223  0   50   1010
8          0    29     67    68   323  0   59    546
9          0    29    132    23    50  0   26    260
10         0    27    115    45   279  1  209    676
All        3  6372  21170  1453  2377  1  457  31833

In [33]:
#Comparing actual vs predicted values
#On average, can predict correctly 33.8% of the time
accuracy = accuracy_score(y_true=y_test, y_pred=y_test_pred_nb)
accuracy.round(3)

0.338

In [34]:
#33.3% classified 0 stay, actually were 0 stay...
precision = precision_score(y_true=y_test, y_pred=y_test_pred_nb, average = None)
precision.round(3)

/Users/dannica/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([0.333, 0.352, 0.338, 0.287, 0.   , 0.309, 0.   , 0.   , 0.   ,
       0.   , 0.457])

In [35]:
#0% of the things that are actually 0 stay, we were able to correctly categorize...
recall = recall_score(y_true=y_test, y_pred=y_test_pred_nb, average = None)
recall.round(3)

array([0.   , 0.283, 0.82 , 0.076, 0.   , 0.217, 0.   , 0.   , 0.   ,
       0.   , 0.309])

## Decide Max Depth

In [37]:
for x in range(1,40):
    class_tree = DecisionTreeClassifier(max_depth=x)
    class_tree.fit(X_train, y_train)
    y_train_pred = class_tree.predict(X_train)
    accuracy = accuracy_score(y_true=y_train, y_pred=y_train_pred)
    accuracy.round(3)
    print('DEPTH: '+str(x)+"\t"+'ACCURACY: '+str((accuracy.round(3))))

DEPTH: 1	ACCURACY: 0.304
DEPTH: 2	ACCURACY: 0.354
DEPTH: 3	ACCURACY: 0.367
DEPTH: 4	ACCURACY: 0.38
DEPTH: 5	ACCURACY: 0.392
DEPTH: 6	ACCURACY: 0.394
DEPTH: 7	ACCURACY: 0.402
DEPTH: 8	ACCURACY: 0.407
DEPTH: 9	ACCURACY: 0.412
DEPTH: 10	ACCURACY: 0.419
DEPTH: 11	ACCURACY: 0.428
DEPTH: 12	ACCURACY: 0.44
DEPTH: 13	ACCURACY: 0.455
DEPTH: 14	ACCURACY: 0.474
DEPTH: 15	ACCURACY: 0.498
DEPTH: 16	ACCURACY: 0.526
DEPTH: 17	ACCURACY: 0.557
DEPTH: 18	ACCURACY: 0.592
DEPTH: 19	ACCURACY: 0.63
DEPTH: 20	ACCURACY: 0.67
DEPTH: 21	ACCURACY: 0.709
DEPTH: 22	ACCURACY: 0.748
DEPTH: 23	ACCURACY: 0.784
DEPTH: 24	ACCURACY: 0.818
DEPTH: 25	ACCURACY: 0.848
DEPTH: 26	ACCURACY: 0.874
DEPTH: 27	ACCURACY: 0.897
DEPTH: 28	ACCURACY: 0.916
DEPTH: 29	ACCURACY: 0.932
DEPTH: 30	ACCURACY: 0.946
DEPTH: 31	ACCURACY: 0.957
DEPTH: 32	ACCURACY: 0.967
DEPTH: 33	ACCURACY: 0.974
DEPTH: 34	ACCURACY: 0.98
DEPTH: 35	ACCURACY: 0.985
DEPTH: 36	ACCURACY: 0.989
DEPTH: 37	ACCURACY: 0.991
DEPTH: 38	ACCURACY: 0.994
DEPTH: 39	ACCURACY: 0.995


## Different features

In [38]:
training_features = ['num_visitors','ward_type','deposit','bed_grade','admission_type']
X=health_cleaned[training_features]
y=health_cleaned['stay']

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.10, random_state=42)

In [40]:
class_tree = DecisionTreeClassifier(max_depth=11)
class_tree.fit(X_train, y_train)
y_train_pred = class_tree.predict(X_train)
accuracy = accuracy_score(y_true=y_train, y_pred=y_train_pred)
accuracy.round(3)
print('DEPTH: '+str(x)+"\t"+'ACCURACY: '+str((accuracy.round(3))))

DEPTH: 39	ACCURACY: 0.409


## Predict Stay 1-3

In [41]:
stay123 = health_cleaned[health_cleaned['stay'].isin([1, 2, 3])]
stay123

hosp_code  hosp_type  city_code  hosp_region  rooms_available  \
2              10          1          1            1                2   
5              23          3          6            1                2   
9              10          1          1            1                2   
10             22          6          9            2                2   
11             26          2          2            2                4   
...           ...        ...        ...          ...              ...   
318319         26          2          2            2                2   
318320          6          3          6            1                3   
318321         24          3          1            1                2   
318322          7          3          4            1                3   
318323         11          2          2            2                3   

        department  ward_type  ward_code  bed_grade  patient_id  \
2                1          1          1          2       31397   
5                1          1          0          2       31397   
9                2          1          1          3       31397   
10               0          1          3          2       31397   
11               0          0          2          1       31397   
...            ...        ...        ...        ...         ...   
318319           1          0          2          3       36018   
318320           0          2          0          4       86499   
318321           1          2          1          4         325   
318322           2          0          0          4      125235   
318323           1          2          2          3       91081   

        admission_type  severity  num_visitors  age  deposit  stay  
2                    1         0             2    5     4745     3  
5                    1         0             2    5     4449     1  
9                    1         0             2    5     6056     3  
10                   2         0             2    5     5797     2  
11                   2         0             2    5     5993     1  
...                ...       ...           ...  ...      ...   ...  
318319               0         2             3    1     8308     2  
318320               0         1             3    4     4144     1  
318321               2         1             4    8     6699     3  
318322               0         2             3    7     4235     1  
318323               1         2             5    1     3761     1  

[220711 rows x 16 columns]

In [44]:
X=stay123.drop('stay',axis=1)
y=stay123['stay']

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.10, random_state=42)

In [46]:
from sklearn.tree import DecisionTreeClassifier
class_tree = DecisionTreeClassifier(max_depth=11)
class_tree.fit(X_train, y_train)
y_train_pred = class_tree.predict(X_train)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_true=y_train, y_pred=y_train_pred)
accuracy.round(3)
print('DEPTH: '+str(11)+"\t"+'ACCURACY: '+str((accuracy.round(3))))

DEPTH: 11	ACCURACY: 0.558


In [47]:
health_cleaned.isnull().sum()

hosp_code          0
hosp_type          0
city_code          0
hosp_region        0
rooms_available    0
department         0
ward_type          0
ward_code          0
bed_grade          0
patient_id         0
admission_type     0
severity           0
num_visitors       0
age                0
deposit            0
stay               0
dtype: int64

## Change stay 4-10, to 4

In [48]:
health_cleaned.stay.unique()

array([ 0,  4,  3,  1,  5,  2,  7, 10,  8,  6,  9])

In [49]:
health_cleaned['stay'] = health_cleaned['stay'].replace([4,5,6,7,8,9,10],4)

In [50]:
health_cleaned.stay.unique()

array([0, 4, 3, 1, 2])

In [52]:
X=health_cleaned.drop('stay',axis=1)
y=health_cleaned['stay']

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.10, random_state=42)

In [54]:
from sklearn.tree import DecisionTreeClassifier
class_tree = DecisionTreeClassifier(max_depth=11)
class_tree.fit(X_train, y_train)
y_train_pred = class_tree.predict(X_train)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_true=y_train, y_pred=y_train_pred)
accuracy.round(3)
print('DEPTH: '+str(11)+"\t"+'ACCURACY: '+str((accuracy.round(3))))

DEPTH: 11	ACCURACY: 0.484


In [55]:
for x in range(1,26):
    class_tree = DecisionTreeClassifier(max_depth=x)
    class_tree.fit(X_train, y_train)
    y_train_pred = class_tree.predict(X_train)
    accuracy = accuracy_score(y_true=y_train, y_pred=y_train_pred)
    accuracy.round(3)
    print('DEPTH: '+str(x)+"\t"+'ACCURACY: '+str((accuracy.round(3))))

DEPTH: 1	ACCURACY: 0.384
DEPTH: 2	ACCURACY: 0.413
DEPTH: 3	ACCURACY: 0.433
DEPTH: 4	ACCURACY: 0.444
DEPTH: 5	ACCURACY: 0.45
DEPTH: 6	ACCURACY: 0.453
DEPTH: 7	ACCURACY: 0.461
DEPTH: 8	ACCURACY: 0.464
DEPTH: 9	ACCURACY: 0.469
DEPTH: 10	ACCURACY: 0.475
DEPTH: 11	ACCURACY: 0.484
DEPTH: 12	ACCURACY: 0.494
DEPTH: 13	ACCURACY: 0.508
DEPTH: 14	ACCURACY: 0.525
DEPTH: 15	ACCURACY: 0.546
DEPTH: 16	ACCURACY: 0.571
DEPTH: 17	ACCURACY: 0.599
DEPTH: 18	ACCURACY: 0.63
DEPTH: 19	ACCURACY: 0.663
DEPTH: 20	ACCURACY: 0.696
DEPTH: 21	ACCURACY: 0.73
DEPTH: 22	ACCURACY: 0.763
DEPTH: 23	ACCURACY: 0.795
DEPTH: 24	ACCURACY: 0.825
DEPTH: 25	ACCURACY: 0.852
